version: 2

sources:
  - name: dwh
    schema: CORE
    loader: dbt_job
    tables:
      - name: dim_agency
        description: "TODO"      
      - name: fact_policy
        description: "TODO"      
